services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: gorm
      POSTGRES_PASSWORD: gorm
      POSTGRES_DB: gorm
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: gorm
      DB_PASSWORD: gorm
      DB_NAME: gorm
      DB_PORT: 5432
      TZ: America/Sao_Paulo
    ports:
      - "8080:8080"

volumes:
  pgdata:
